[project]
name = "python-flask-pdf"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "weasyprint",
    "python-dotenv",
    "jinja2",
    "fonttools>=4.60.1",
    "flask",
    "pypdf",
]

[tool.setuptools]
py-modules = ["app"]
packages = []

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
